site_name: Pangea
site_url: https://bitnation.co
repo_url: https://github.com/Bit-Nation/pangea-developer-documentation
site_dir: docs_build
pages:
  - Getting Started: index.md
  - Docs: rough_doc.md
theme: readthedocs