site_name: Pangea
site_url: https://bitnation.co
repo_url: https://github.com/Bit-Nation/pangea-developer-documentation
site_dir: docs_build
pages:
  - Start here: index.md
  # - Docs: rough_doc.md
  - Hands on: hands_on.md
  - VM functionality: vm_functionality.md
theme: readthedocs